### ISSUE TITLE
How do you use this ?

### ISSUE THREAD

**Issue by hugoam** [crosire/vs-toolsets#1]
I'm very interested in using this, however I can't figure it out. Could you write a very short walkthrough ?
When I try to add Emscripten platform to an existing project it just fails at various points.
I would be interested to know what the project file should contain to have a correct solution with Emscripten as a target platform.

**Comment by crosire** [comment]
Should work now. Just copy the files as specified in the readme, create a new console project in Visual Studio, open the Configuration Manager, add the Emscripten platform to your project (make sure you select the "\<Empty\>" option for "Copy settings from") and set the Configuration Type to "HTML + JavaScript (.html)" in your project properties.

**Comment by hugoam** [comment]
I somehow managed to write a bare minimum project file that worked in the mean time.
Thanks for the fix !
I have another small issue : it seems when compiling that `__EMSCRIPTEN__` is not defined which causes some compilation errors in emscripten std library. I suppose that should be handled by the compiler itself so I'm wondering what's wrong ?

**Comment by crosire** [comment]
`__EMSCRIPTEN__` should be defined (see https://github.com/crosire/vs-toolsets/blob/master/Platforms/Emscripten/Platform.Common.props#L67). You can try setting it in the project properties manually though,

**Comment by hugoam** [comment]
My issue was again, somewhere else than what I thought. Thanks :)
