### ISSUE TITLE
Change Browser

### ISSUE THREAD

**Issue by alexmogu** [crosire/vs-toolsets#4]
Hi everybody, thanks for this tool, it is really useful. But we have a question: how can we change the web browser launched when we click on "Web Browser Debugger" button?

Thank you!

**Comment by crosire** [comment]
You can change the debugger type to "Local Windows Debugger" and start your browser of choice with the output HTML file as argument. But Javascript debugging won't work with anything except IE.

**Comment by fatmingwang** [comment]
Hello 
the Debugger Type don't have Local Windows Debugger
it show
Native only
Managed only
Mixed
Auto
script
Did I miss something?
Is it possible to set something then run with the browser I need?

**Comment by crosire** [comment]
I was not talking about the code type to debug, I was talking about the debugger configuration. You can switch it by clicking on the downward arrow on the debug button in the menu bar (the one with the green play button).
