### ISSUE TITLE
Works great so far

### ISSUE THREAD

**Issue by sasmaster** [crosire/vs-toolsets#5]
Thanks, man! It made my life easier )))

**Comment by fatmingwang** [comment]
vs-toolsets also works fine with VS2019

copy file(vs-toolsets) into
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160

install individual components 
MSVC v140 - VS 2015 c++ build tools(v14.00)
